const express = require('express');
const router = express.Router();
const authController = require('../controllers/authController');
router.post('/send-otp', authController.sendOtp);
router.post('/verify-otp', authController.verifyOtp);
router.post('/check-user', authController.checkUser);
router.post('/save-user',authController.saveUser);
router.post('/sign-out', authController.signOut); 
router.post('/admin-logout', authController.adminLogout); 
router.get('/check-auth', authController.checkAuth);
router.get('/check-admin', authController.checkAdminAuth);
router.post('/verifyAuth-token', authController.verifyFirebaseToken);
router.get('/profile', authController.checkAuthMiddleware,authController.fetchUserProfile);
router.get('/profileAdmin', authController.checkAdminAuthMiddleware,authController.fetchUserProfile);
router.put('/profileUpdate', authController.updateUserProfile);
router.post('/verify-phoneUser', authController.verifyPhoneUser);
router.post('/admin-user', authController.sendAdminOtp);
router.post('/verify-admin-otp', authController.verifyAdminOtp);
router.get('/profiles', authController.fetchAllProfiles);
router.get('/profiles/:id', authController.fetchProfileById);
module.exports = router;
